name: 💡 Feature request
description: Suggest an idea for this project
labels: [enhancement]
body:
  - type: textarea
    id: relation
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
      placeholder: Description
  - type: textarea
    id: background
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: Purpose
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: Alternative
    validations:
      required: true